/***************************************************************************************
* \file LocalVoice_training.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef LOCALVOICE_TRAINING_H
#define LOCALVOICE_TRAINING_H

#include <stdint.h>

#define LOCALVOICE_TRAINING_NUM_INTENTS 15
#define LOCALVOICE_TRAINING_NUM_COMMANDS 85
#define LOCALVOICE_TRAINING_NUM_VARIABLES 0
#define LOCALVOICE_TRAINING_NUM_VARIABLE_PHRASES 0
#define LOCALVOICE_TRAINING_NUM_UNIT_PHRASES 16
#define LOCALVOICE_TRAINING_INTENT_MAP_ARRAY_TOTAL_SIZE 170
#define LOCALVOICE_TRAINING_UNIT_PHRASE_MAP_ARRAY_TOTAL_SIZE 85

extern const char* LocalVoice_training_intent_name_list[LOCALVOICE_TRAINING_NUM_INTENTS];

extern const char* LocalVoice_training_variable_name_list[LOCALVOICE_TRAINING_NUM_VARIABLES];

extern const char* LocalVoice_training_variable_phrase_list[LOCALVOICE_TRAINING_NUM_VARIABLE_PHRASES];

extern const char* LocalVoice_training_unit_phrase_list[LOCALVOICE_TRAINING_NUM_UNIT_PHRASES];

extern const int LocalVoice_training_intent_map_array[LOCALVOICE_TRAINING_INTENT_MAP_ARRAY_TOTAL_SIZE];

extern const int LocalVoice_training_intent_map_array_sizes[LOCALVOICE_TRAINING_NUM_COMMANDS];

extern const int LocalVoice_training_variable_phrase_sizes[LOCALVOICE_TRAINING_NUM_VARIABLES];

extern const int LocalVoice_training_unit_phrase_map_array[LOCALVOICE_TRAINING_UNIT_PHRASE_MAP_ARRAY_TOTAL_SIZE];

extern const int LocalVoice_training_unit_phrase_map_array_sizes[LOCALVOICE_TRAINING_NUM_COMMANDS];

#endif // LOCALVOICE_TRAINING_H
