/***************************************************************************************
* \file LocalVoice_training_U55_CMDmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef LOCALVOICE_TRAINING_U55_CMDMODEL_H
#define LOCALVOICE_TRAINING_U55_CMDMODEL_H

extern const char LocalVoice_training_CMDmodeldata[];
#define LOCALVOICE_TRAINING_CMDMODELDATA_SIZE 42804

#endif // LOCALVOICE_TRAINING_U55_CMDMODEL_H
